# Heat Map

In [1]:
# 导入beakerx库及其他所需库文件
from beakerx import *
from beakerx.object import beakerx

import numpy as np
import random

In [2]:
data = np.random.randint(0,10,30).reshape(6,5)

print(data)

HeatMap(
    title = "BeakerX/Heat Map Demo 热力图演示 #1",
    xLabel = "X轴",
    yLabel = "Y轴",
    data = data,
    legendPosition = LegendPosition(position = LegendPosition.Position.BOTTOM),
    # color = GradientColor.WHITE_BLUE, # BROWN_RED_YELLOW / GREEN_YELLOW_WHITE / WHITE_BLUE
    color = GradientColor([Color(255,255,0), Color(255,32,0)]),
    initWidth = 540,
    initHeight = 360
)

[[3 0 7 1 6]
 [7 4 8 3 2]
 [0 3 8 4 9]
 [0 0 0 2 3]
 [7 3 6 3 8]
 [4 1 1 9 9]]


# Category Plot

In [3]:
data = np.random.randint(1,99,12).reshape(3, 4)

print(data)

cp1 = CategoryPlot(
    title = "BeakerX/Category Plot Demo 分类图形演示 #1",
    xLabel = "X轴",
    yLabel = "Y轴",
    categoryNames = ['系列%s' % x for x in range(1, len(data[0])+1)],
    categoryMargin= 0.5,
    orientation= PlotOrientationType.VERTICAL # PlotOrientationType.HORIZONTAL
)

# 加入分类柱状图
cp1.add(
    CategoryBars(
        value = data,
        # base = [(-1+x)*10 for x in range(len(data))],
        seriesNames= ['%s号货品' % x for x in range(1, len(data)+1)],
        showItemLabel = True,
        labelPosition= LabelPositionType.VALUE_OUTSIDE,
        outlineColor= [Color.black, Color.red],
        # centerSeries= False,
        width = 0.5
    )
)

[[98 20 97 49]
 [38 90 64 83]
 [60  5 11 61]]


In [4]:
data = np.random.randint(1,99,8).reshape(2, 4)
base = [(-1+x)*10 for x in range(len(data))]

print(data)
print(base)

cp2 = CategoryPlot(
    title = "BeakerX/Category Plot Demo 分类图形演示 #2",
    xLabel = "X轴",
    yLabel = "支出范围"
)

cp2.add(YAxis(label= "第二Y轴", upperMargin= 1))

# 加入杆图
cp2.add(
    CategoryStems(
        value = data,
        base = base,
        color = [Color(192,192,255), Color(255,192,192)],
        seriesNames = ['支出范围%s' % x for x in range(1, len(data)+1)],
        showItemLabel = True,
        width = 30
    )
)

# 加入线段(对应第二Y轴)
cp2.add(
    CategoryLines(
        value = data,
        yAxis = "第二Y轴",
        style = [StrokeType.DASH, StrokeType.DOT],
        seriesNames = ['第二Y轴曲线%s' % x for x in range(1, len(data)+1)],
        width = 3
    )
)

# 加入数据点(对应第二Y轴)
cp2.add(
    CategoryPoints(
        value = data,
        yAxis = "第二Y轴",
        seriesNames = ['第二Y轴数据点%s' % x for x in range(1, len(data)+1)],
        size = 15
    )
)

[[46 69 83 16]
 [ 6 93 12 86]]
[-10, 0]


In [5]:
data = np.random.randint(1,99,12).reshape(3,4)
base = [(-1+x)*20 for x in range(len(data))]

print(data)
print(base)

cp3 = CategoryPlot(
    title = "BeakerX/Category Plot Demo 分类图形演示 #2",
    xLabel = "X轴",
    yLabel = "支出范围"
)

cp3.add(
    CategoryArea(
        value = data,
        base = base,
        color = [Color(192,192,0), Color(0,192,192,192), Color(255,128,128,192)]
    )
)

for i in range(len(base)):
    cp3.add(
        ConstantLine(
            y = base[i],
            style = [StrokeType.DOT, StrokeType.DASH, StrokeType.DASHDOT][i%3] ,
            color = Color.gray,
            showLabel = True
        )
    )
    
cp3

[[32 67 17 80]
 [88 41 58 90]
 [80 28 35 32]]
[-20, 0, 20]
